version: '2'

services:

  php:
    build: .
    volumes: ['./:/app']

  composer:
    extends: { service: php }
    entrypoint: ['composer']

  phpunit:
    extends: { service: php }
    entrypoint: ['./vendor/bin/phpunit']
    links: ['mysql']

  mysql:
    image: mysql:5.5
    environment: ['MYSQL_ROOT_PASSWORD=secret']
    volumes: ['mysql:/var/lib/mysql']

volumes:
  mysql:
