#!/usr/bin/env php
<?php
/**
 * Mysql Import.
 *
 * PHP version 5
 *
 * @category   Script
 *
 * @author     Francesco Bianco <bianco@javanile.org>
 * @license    https://goo.gl/KPZ2qI  MIT License
 * @copyright  2015-2018 Javanile
 */
require_once __DIR__.'/../../autoload.php';

use Javanile\MysqlImport\MysqlImport;

$app = new MysqlImport($_ENV, array_slice($argv, 1));

echo $app->run() . "\n";

exit($app->getExitCode());
