#!/usr/bin/env php
<?php
/**
 * Mysql Import.
 *
 * PHP version 5
 *
 * @category   Script
 *
 * @author     Francesco Bianco <bianco@javanile.org>
 * @license    https://goo.gl/KPZ2qI  MIT License
 * @copyright  2015-2019 Javanile
 */

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} else {
    require_once __DIR__ . '/../../autoload.php';
}

use Javanile\MysqlImport\MysqlImport;

$env = [];

foreach ([
    'MYSQL_HOST',
    'MYSQL_PORT',
    'MYSQL_DATABASE',
    'MYSQL_USER',
    'MYSQL_PASSWORD',
    'MYSQL_ROOT_PASSWORD',
    'DB_HOST',
    'DB_PORT',
    'DB_NAME',
    'DB_USER',
    'DB_PASSWORD',
    'DB_ROOT_PASSWORD',
    'WORDPRESS_DB_HOST',
    'WORDPRESS_DB_NAME',
    'WORDPRESS_DB_USER',
    'WORDPRESS_DB_PASSWORD',
] as $var) {
    if (getenv($var) !== false) {
        $env[$var] = getenv($var);
    }
}

$app = new MysqlImport($env, array_slice($argv, 1));

echo $app->run() . "\n";

exit($app->getExitCode());
